firstapp/urls.py
from firstapp import views
from django.conf.urls import url
app_name='firstapp'    #-----constant variable should be linked in urls files
urlpatterns=[
    url(r'^about/$',views.about,name="about"),
    url(r'^content1/$', views.content1,name="content1"),
    url(r'^content2/$',views.content2,name="content2"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.login, name="login"),
    url(r'^viewdata/$', views.viewdata, name="viewdata"),
    url(r'^fetchingonevalue/$', views.fetchingonevalue, name="fetchdata"),
    url(r'^imageform/$', views.imageform, name="image"),
    url(r'^updateform/$', views.updateform, name="update"),
    url(r'^delete/$', views.deletedata, name="delete"),
    url(r'^updatedata/$', views.action, name="update"),
    url(r'^imageviewdata/$', views.imageviewdata, name="imagedata"),
    url(r'^imagedelete/$', views.deleteimageformdata, name="imagedelete"),
    url(r'^imageupdate/$', views.imageupdate, name="imageudate"),

]

firstproject/urls.py
from django.contrib import admin
from django.urls import path
from firstapp import views
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index),
    url(r'^home/$',views.home),
    url(r'^user/', include('firstapp.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert("Successfully Registered");
    </script>
    {% endif %}
    <label>Name</label>
    <input type="text" name="rolename"><br/>
    <input type="submit" name="b1" value="Inser-Data"/>
</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Master page</title>
</head>
<body>
<div style="height:200px;border:1px solid red;">
    <h1>This is heading</h1>
    </div><br/>
<div style="height:200px;border:1px solid blue;">
{% block content %}


    {% endblock %}

</div><br/>
<div style="height:200px;border:1px solid grey;">
    <h1>This is heading2</h1>
</div><br/>
</body>
</html>

templates/content1.html
{% extends 'base.html' %}
{% block content %}
<h1>This is content page1</h1>
{% endblock %}

templates/content2.html
{% extends 'base.html' %}
{% block content %}
<h1>This is content page2</h1>
<p>This is django class</p>
{% endblock %}

templates/fetchingonevalue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if d %}
{{d.userFullName}}
{{d.userEmail}}
{{d.userPassword}}
{{d.userMobile}}
{% endif %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="/assets/css/mystyle.css" type="text/css" rel="stylesheet">
    <script src="/assets/javascript/jquery.js" type="text/javascript">
</script>

    </head>
<body >
<h1>Welcome to first page of project</h1>
<a href="{% url 'firstapp:about' %}">About</a>
<br/>  <!----{{a}}-----//printing statement---->
<img src="/assets/images/image2.jpg" height="500px" width="500px"/><br/>
<div>
   <p id="p1">Hide</p>
    <p id="p2">Show</p>
</div><br/>
<div id="d1">
    Hello
</div>

 <script type="text/javascript">
     $(document).ready(function() {
             $("#p1").click(function ()  {
             $("#d1").hide();
                });

             $("#p2").click(function ()  {
                     $("#d1").show();
             });

         });
    </script>

</body>
</html>

templates/imagedelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/imageform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert("Successfully Registered");
    </script>
    {% endif %}
    <label>Name</label>
    <input type="text" name="username" placeholder="Name here"><br/>
    <label>EmailId</label>
    <input type="email" name="useremail" placeholder="Email here"/><br/>
    <label>Password</label>
    <input type="password" name="userpassword" placeholder="password here"><br/>
    <label>Mobile</label>
    <input type="text" name="usermobile" placeholder="Contact here"><br/>
    <label>Image</label>
    <input type="file" name="userimage"><br/>
    <input type="submit"  value="submit">
</form>
</body>
</html>

templates/imageupdateform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert("Successfully Registered");
    </script>
    {% endif %}

    <label>UserFullName</label>
    <input type="text" value="{{b.userFullName}}" name="username" /><br/>
    <label>EmailId</label>
    <input type="email" value="{{b.userEmail}}" name="useremail" disabled/><br/>
    <label>Password</label>
    <input type="password" value="{{b.userPassword}}" name="userpassword" placeholder="password here"><br/>
    <label>Mobile</label>
    <input type="text" value="{{b.userMobile}}" name="usermobile" placeholder="Contact here"><br/>
    <label>Image</label>
    <img src="/media/{{b.userImage}}" height="70px" width="70px">
    <input type="file" name="userimage" id="userimage"><br/>
    <input type="submit"  value="Update-Data">
</form>
</body>
</html>

templates/imageviewdata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table border="1px solid black">
    <tr>
        <td>FullName</td>
        <td>Email</td>
        <td>Password</td>
        <td>Mobile</td>
        <td>Image</td>
        <td>Action-Delete</td>
        <td>Image-update</td>
    </tr>
{% if b %}
{% for i in b %}

    <tr>
        <td>{{i.userFullName}}</td>
        <td>{{i.userEmail}}</td>
        <td>{{i.userPassword}}</td>
        <td>{{i.userMobile}}</td>
        <td><img src='/media/{{i.userImage}}' height="70px" width="70px"/></td>
        <td><a href="/user/imagedelete/?id={{i.userEmail}}">Delete-Data</a></td>
        <td><a href="/user/imageupdate/?id={{i.userEmail}}">Edit</a></td>
    </tr>
{% endfor %}
{% endif %}
</table>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Form</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert("Successfully Registered");
    </script>
    {% endif %}
    <label>Name</label>
    <input type="text" name="username" placeholder="Name here"><br/>
    <label>EmailId</label>
    <input type="email" name="useremail" placeholder="Email here"/><br/>
    <label>Password</label>
    <input type="password" name="userpassword" placeholder="password here"><br/>
    <label>Mobile</label>
    <input type="text" name="usermobile" placeholder="Contact here"><br/>
    <input type="submit"  value="submit">
</form>
</body>
</html>

templates/updatedata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert("Successfully Registered");
    </script>
    {% endif %}
    <label>EmailId</label>
    <input type="text" value="{{a.userEmail}}" id="userEmail" name="userEmail"/><br>
    <label>Password</label>
    <input type="password" name="userpassword" placeholder="password here"/><br/>
    <label>Mobile</label>
    <input type="text" name="usermobile" placeholder="Contact here"/><br/>
    <input type="submit"  value="Update-Data"/>
</form>
</body>
</html>

templates/updateform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert("Successfully Registered");
    </script>
    {% endif %}
    <label>EmailId</label>
    <input type="email" name="useremail" placeholder="Email here"/><br/>
    <label>Password</label>
    <input type="password" name="userpassword" placeholder="password here"><br/>
    <label>Mobile</label>
    <input type="text" name="usermobile" placeholder="Contact here"><br/>
    <input type="submit"  value="Update-Data">
</form>
</body>
</html>

templates/viewdata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<table border="1px solid black">
    <tr>
        <td>FullName</td>
        <td>Email</td>
        <td>Password</td>
        <td>Mobile</td>
        <td>Image</td>
        <td>Action-Delete</td>
        <td>Action-Update</td>
    </tr>
{% if d %}
{% for i in d %}

    <tr>
        <td>{{i.userFullName}}</td>
        <td>{{i.userEmail}}</td>
        <td>{{i.userPassword}}</td>
        <td>{{i.userMobile}}</td>
        <td><img src='/media/{{i.userImage}}' height="70px" width="70px"/></td>
        <td><a href="/user/delete/?id={{i.userEmail}}">Delete-Data</a></td>
        <td><a href="/user/updatedata/?id={{i.userEmail}}">Edit</a></td>
    </tr>
{% endfor %}
{% endif %}
</table>
</body>
</html>